# Generated by Django 2.2.10 on 2020-05-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation',
            name='metafield',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='metamodel.Metafield'),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='platform',
            field=models.CharField(choices=[('dsl', 'DSL'), ('gbq', 'GBQ'), ('bulkd', 'Bulk Data'), ('webapp', 'Web App')], max_length=200, verbose_name='platform'),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='profile',
            field=models.CharField(blank=True, choices=[('public', 'public'), ('private', 'private'), ('NIH', 'NIH'), ('hidden', 'hidden')], max_length=200, verbose_name='profile / visibility'),
        ),
        migrations.AlterField(
            model_name='metafield',
            name='source',
            field=models.CharField(choices=[('publications', 'publications'), ('grants', 'grants'), ('patents', 'patents'), ('clinical_trials', 'clinical_trials'), ('policy_documents', 'policy_documents'), ('researchers', 'researchers'), ('organizations', 'organizations'), ('datasets', 'datasets')], max_length=200, verbose_name='source'),
        ),
    ]
