# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-24 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBPediaEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='title')),
                ('uri', models.URLField(max_length=300)),
                ('dbtype', models.CharField(blank=True, max_length=200, verbose_name='dbtype')),
                ('description', models.TextField(blank=True, verbose_name='description (put everything in here for now)')),
            ],
            options={
                'verbose_name': 'DBPediaEntity',
                'verbose_name_plural': 'DBPediaEntitys',
            },
        ),
        migrations.CreateModel(
            name='SGDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='title')),
                ('uri', models.URLField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='author')),
                ('pubyear', models.IntegerField(blank=True, null=True, verbose_name='publication year')),
                ('description', models.TextField(blank=True, verbose_name='description (put everything in here for now)')),
                ('dbentities', models.ManyToManyField(to='dbpedialinks.DBPediaEntity')),
            ],
            options={
                'verbose_name': 'SGDocument',
                'verbose_name_plural': 'SGDocuments',
            },
        ),
    ]
