# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-01 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbpedialinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbpediaentity',
            options={'ordering': ['title'], 'verbose_name': 'DBPedia Entity', 'verbose_name_plural': 'DBPedia Entities'},
        ),
        migrations.AlterModelOptions(
            name='sgdocument',
            options={'ordering': ['uri'], 'verbose_name': 'SGDocument', 'verbose_name_plural': 'SGDocuments'},
        ),
        migrations.AddField(
            model_name='dbpediaentity',
            name='totarticles',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tot associated articles'),
        ),
    ]
