# Generated by Django 2.1.3 on 2018-11-29 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbpedialinks', '0002_auto_20180501_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('subject1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject1', to='dbpedialinks.DBPediaEntity')),
                ('subject2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject2', to='dbpedialinks.DBPediaEntity')),
            ],
        ),
        migrations.AddField(
            model_name='dbpediaentity',
            name='top_rel_subjects',
            field=models.ManyToManyField(through='dbpedialinks.Subject_Rel', to='dbpedialinks.DBPediaEntity'),
        ),
    ]
