# Generated by Django 2.2.10 on 2021-01-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbpedialinks', '0003_auto_20181129_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_rel',
            name='subject1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_subject_in_relations', to='dbpedialinks.DBPediaEntity'),
        ),
        migrations.AlterField(
            model_name='subject_rel',
            name='subject2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_object_in_relations', to='dbpedialinks.DBPediaEntity'),
        ),
    ]
